import { UserProfile } from '../../types';

/**
 * Akun Root Administrator Sistem.
 * Seluruh akun demo operasional telah dibersihkan sesuai instruksi.
 * Akun ini digunakan untuk inisialisasi awal dan pendaftaran akun-akun nyata.
 */
export const INITIAL_SYSTEM_USERS: (UserProfile & { defaultPassword: string })[] = [
  {
    id: 'usr-admin',
    nik: 'admin',
    name: 'ADMIN',
    department: 'admin',
    role: 'admin',
    email: 'lms00000@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms10001',
    nik: 'LMS10001',
    name: 'Daffa',
    department: 'rnd',
    role: 'staff',
    email: 'lms10001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms10002',
    nik: 'LMS10002',
    name: 'Tanzil',
    department: 'rnd',
    role: 'supervisor',
    email: 'lms10002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms10003',
    nik: 'LMS10003',
    name: 'Lanny',
    department: 'rnd',
    role: 'manager',
    email: 'lms10003@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms20001',
    nik: 'LMS20001',
    name: 'Ayu',
    department: 'quality',
    role: 'staff',
    email: 'lms20001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms20002',
    nik: 'LMS20002',
    name: 'Lala',
    department: 'quality',
    role: 'supervisor',
    email: 'lms20002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms20003',
    nik: 'LMS20003',
    name: 'Michael',
    department: 'quality',
    role: 'manager',
    email: 'lms20003@larassanti.co.id',
    defaultPassword: 'laras123',
    specificAccess: [{ moduleId: 'rnd', accessLevel: 'read' }],
  },
  {
    id: 'usr-lms30001',
    nik: 'LMS30001',
    name: 'Heni',
    department: 'warehouse',
    role: 'staff',
    email: 'lms30001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms30002',
    nik: 'LMS30002',
    name: 'Maulana',
    department: 'warehouse',
    role: 'supervisor',
    email: 'lms30002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms30003',
    nik: 'LMS30003',
    name: 'Haryani',
    department: 'warehouse',
    role: 'manager',
    email: 'lms30003@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms40001',
    nik: 'LMS40001',
    name: 'Lisa',
    department: 'production',
    role: 'staff',
    email: 'lms40001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms40002',
    nik: 'LMS40002',
    name: 'Ilham',
    department: 'production',
    role: 'supervisor',
    email: 'lms40002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms40003',
    nik: 'LMS40003',
    name: 'Ika Suci',
    department: 'production',
    role: 'manager',
    email: 'lms40003@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms50001',
    nik: 'LMS50001',
    name: 'Heri',
    department: 'ppic',
    role: 'staff',
    email: 'lms50001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms50002',
    nik: 'LMS50002',
    name: 'Shinta',
    department: 'ppic',
    role: 'supervisor',
    email: 'lms50002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms50003',
    nik: 'LMS50003',
    name: 'Adha Winatie',
    department: 'ppic',
    role: 'manager',
    email: 'lms50003@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms90001',
    nik: 'LMS90001',
    name: 'Hermansyah Rusli',
    department: 'management',
    role: 'manager',
    email: 'lms90001@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms90002',
    nik: 'LMS90002',
    name: 'Herlina',
    department: 'management',
    role: 'manager',
    email: 'lms90002@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms90003',
    nik: 'LMS90003',
    name: 'Dewi Sartika M',
    department: 'management',
    role: 'manager',
    email: 'lms90003@larassanti.co.id',
    defaultPassword: 'laras123',
  },
  {
    id: 'usr-lms90004',
    nik: 'LMS90004',
    name: 'Tita',
    department: 'management',
    role: 'supervisor',
    email: 'lms90004@larassanti.co.id',
    defaultPassword: 'laras123',
  },
];

// Alias untuk kompatibilitas sementara
export const DEMO_USERS = INITIAL_SYSTEM_USERS;

